/**
 * Lightweight data-driven blog. Posts are authored here as structured content
 * (no external CMS/DB), so the listing and article routes stay fully static.
 * Additional long-form guides live in ./blog-extra and are merged below.
 */
import { EXTRA_POSTS } from "./blog-extra";
import { BLOG_HEROES } from "./blog-heroes";

export type Block =
  | { type: "p"; text: string }
  | { type: "h2"; text: string }
  | { type: "h3"; text: string }
  | { type: "ul"; items: string[] }
  | { type: "ol"; items: string[] }
  | { type: "table"; headers: string[]; rows: string[][] }
  | { type: "callout"; title: string; items: string[] }
  | { type: "faq"; items: { q: string; a: string }[] };

export type Post = {
  slug: string;
  title: string;
  excerpt: string;
  category: string;
  date: string; // ISO
  readingMinutes: number;
  heroImage?: { src: string; alt: string };
  links?: { label: string; href: string }[];
  body: Block[];
};

export const POSTS: Post[] = [
  {
    slug: "iptv-pour-senior",
    title: "IPTV pour senior : le guide simple et rassurant",
    excerpt:
      "Un guide clair pour profiter de l'IPTV après 60 ans : choisir un appareil facile, une application simple, et regarder ses chaînes sans se compliquer la vie.",
    category: "Guide",
    date: "2026-08-28",
    readingMinutes: 7,
    heroImage: {
      src: "/images/blog-iptv-senior.jpg",
      alt: "Personnes regardant tranquillement la télévision en streaming sur une grande Smart TV dans un salon",
    },
    links: [
      { label: "Le guide du meilleur IPTV", href: "/meilleur-iptv" },
      { label: "Installer sur Samsung", href: "/appareils/samsung" },
      { label: "Installer sur LG", href: "/appareils/lg" },
      { label: "Installer sur Android TV", href: "/appareils/android-tv" },
      { label: "Questions fréquentes", href: "/faq/questions-frequentes" },
    ],
    body: [
      { type: "p", text: "L'IPTV n'a rien de compliqué, même si le mot fait un peu technique. Il s'agit simplement de regarder la télévision par internet, comme avec une box classique, mais avec beaucoup plus de chaînes et de films. Ce guide explique l'essentiel, calmement, sans jargon inutile." },
      { type: "h2", text: "De quoi a-t-on besoin ?" },
      { type: "p", text: "Trois choses suffisent : une bonne connexion internet, un appareil pour regarder (votre télévision ou un petit boîtier), et une application. Rien d'autre. Si vous avez déjà internet à la maison et une télévision récente, vous êtes prêt." },
      { type: "h2", text: "Quel appareil choisir pour rester simple ?" },
      { type: "p", text: "Le plus simple est d'utiliser directement une Smart TV, sans matériel supplémentaire. Les téléviseurs Samsung et LG conviennent très bien et se manient à la télécommande habituelle." },
      { type: "ul", items: ["Une Smart TV Samsung ou LG : rien à brancher, tout se fait à l'écran", "Un boîtier Android TV : une petite télécommande claire, idéale si la télé n'est pas connectée", "Une clé Fire TV Stick : économique, se branche derrière la télévision"] },
      { type: "p", text: "Si vous hésitez, une télévision Samsung ou LG reste le choix le plus reposant." },
      { type: "h2", text: "Quelle application ?" },
      { type: "p", text: "Une seule application suffit. Elle sert à afficher vos chaînes. Sur Smart TV, un lecteur comme Smart IPTV ou IPTV Smarters fait très bien l'affaire. On l'installe une fois, et on n'y touche plus : ensuite, on allume et on regarde." },
      { type: "h2", text: "Comment ça se passe au quotidien ?" },
      { type: "p", text: "Vous allumez la télévision, vous ouvrez l'application, et vous choisissez votre chaîne avec la télécommande — exactement comme avant. Le guide des programmes indique ce qui passe maintenant et ensuite. Vous pouvez aussi mettre vos chaînes préférées en favoris pour les retrouver d'un clic." },
      { type: "h2", text: "Et si quelque chose ne marche pas ?" },
      { type: "p", text: "Le petit souci le plus courant est une image qui se fige. Neuf fois sur dix, cela vient d'internet. Il suffit souvent d'éteindre puis rallumer la box internet, ou de rapprocher la télévision de la box. En cas de doute, un e-mail ou un message au support suffit : on vous guide pas à pas." },
      { type: "faq", items: [
        { q: "Est-ce compliqué à utiliser au quotidien ?", a: "Non. Une fois l'application installée, on allume la télévision, on l'ouvre et on choisit sa chaîne à la télécommande, exactement comme avant." },
        { q: "Faut-il acheter du matériel ?", a: "Pas forcément. Une Smart TV Samsung ou LG suffit sans rien brancher. Si votre télévision n'est pas connectée, un petit boîtier ou une clé à brancher règle la question." },
        { q: "Que faire si l'image se fige ?", a: "C'est presque toujours internet. Éteignez puis rallumez la box, ou rapprochez la télévision de la box. En cas de doute, le support vous aide en français." },
        { q: "Peut-on garder ses chaînes préférées sous la main ?", a: "Oui : la fonction favoris permet de regrouper vos chaînes habituelles pour les retrouver d'un seul clic, sans faire défiler la liste." },
      ]},
      { type: "callout", title: "À retenir", items: [
        "Une Smart TV Samsung ou LG suffit, sans matériel supplémentaire.",
        "Une seule application à installer, une seule fois.",
        "On allume, on ouvre l'application, on choisit sa chaîne — comme avant.",
        "En cas de souci : éteindre puis rallumer la box internet règle l'essentiel.",
        "Le support répond en français, par e-mail ou message.",
      ]},
      { type: "p", text: "Choisissez un appareil que vous connaissez déjà, une seule application, et n'hésitez jamais à demander de l'aide. L'IPTV doit vous simplifier la vie, pas la compliquer." },
    ],
  },
  {
    slug: "comment-choisir-son-abonnement-iptv",
    title: "Comment choisir son abonnement IPTV en 2026",
    excerpt:
      "Qualité d'image, stabilité, compatibilité, support : les vrais critères pour choisir un service IPTV fiable et éviter les mauvaises surprises.",
    category: "Guide",
    date: "2026-08-12",
    readingMinutes: 8,
    links: [
      { label: "Reconnaître une arnaque IPTV", href: "/blog/reconnaitre-arnaque-iptv" },
      { label: "Check-list avant de souscrire", href: "/blog/checklist-avant-de-souscrire-un-abonnement-iptv" },
      { label: "Pourquoi l'IPTV coûte moins cher", href: "/blog/pourquoi-iptv-moins-cher" },
      { label: "Nos formules d'abonnement", href: "/abonnement" },
    ],
    body: [
      { type: "p", text: "Vous comparez plusieurs offres IPTV et elles se ressemblent toutes « 50 000 chaînes, 4K, pas cher » ? C'est justement le piège. Le marché est très inégal, et le prix n'est pas le bon boussole. Ce guide vous donne les critères objectifs qui séparent un service fiable d'une offre qui vous décevra — pour choisir en connaissance de cause, pas sur une promesse." },
      { type: "h2", text: "Les critères qui comptent vraiment" },
      { type: "p", text: "Avant de regarder le tarif, évaluez chaque offre sur ces points. Un bon service coche l'ensemble ; une offre douteuse en néglige plusieurs." },
      { type: "table", headers: ["Critère", "Ce qu'il faut regarder", "Signal d'alerte"], rows: [
        ["Stabilité", "Tenue aux heures de pointe, réseau dimensionné", "Coupures fréquentes le soir"],
        ["Qualité réelle", "Encodage H.265, vraie 4K/HDR", "4K « annoncée » mais pixelisée"],
        ["Catalogue", "Chaînes et VOD réellement présentes", "Listes gonflées mais liens morts"],
        ["Compatibilité", "Vos appareils pris en charge", "Fonctionne « que » sur une app obscure"],
        ["Support", "Joignable, en français, réactif", "Aucun contact identifiable"],
        ["Souplesse", "Sans engagement, garantie", "Engagement long imposé"],
      ]},
      { type: "h2", text: "La stabilité, le critère roi" },
      { type: "p", text: "Un service se juge d'abord à sa capacité à tenir un soir de grand match, quand des milliers d'utilisateurs se connectent en même temps. C'est là qu'un réseau bien dimensionné fait la différence entre une soirée fluide et une image qui se fige. Une belle liste de chaînes ne vaut rien si elle coupe au mauvais moment." },
      { type: "h2", text: "Qualité 4K : distinguer l'annonce du réel" },
      { type: "p", text: "Beaucoup d'offres affichent « 4K » sans réellement la proposer. Cherchez la mention d'un encodage moderne (H.265/HEVC) et du HDR : c'est ce qui permet une vraie image Ultra HD sans saturer la connexion. En cas de doute, testez une chaîne 4K sur votre écran avant de vous engager." },
      { type: "h2", text: "La compatibilité avec vos appareils" },
      { type: "p", text: "Vérifiez que le service fonctionne sur le matériel que vous possédez déjà :" },
      { type: "ul", items: [
        "Smart TV Samsung (Tizen) et LG (webOS)",
        "Android TV et boîtiers dédiés",
        "Fire TV Stick et Apple TV",
        "Smartphones, tablettes et ordinateurs",
      ]},
      { type: "h2", text: "Support et garanties : les signes de sérieux" },
      { type: "p", text: "Un support réactif, en français, et une garantie satisfait ou remboursé sont des marqueurs de confiance. Privilégiez les offres sans engagement : elles vous laissent libre de partir si le service déçoit, ce qu'un prestataire sûr de lui n'a aucune raison de craindre." },
      { type: "h2", text: "Combien faut-il payer ?" },
      { type: "p", text: "Le bon prix n'est ni le plus élevé ni le plus bas. Une offre au tarif dérisoire finance rarement des serveurs stables ; une offre au prix correct, avec des formules longues qui réduisent le coût mensuel, est un meilleur pari. Nous expliquons cette logique de prix dans notre article dédié." },
      { type: "h2", text: "Tester avant de s'engager" },
      { type: "p", text: "Le meilleur moyen de trancher reste l'essai : une garantie satisfait ou remboursé vous permet de vérifier la stabilité et la qualité dans vos conditions réelles avant de vous engager sur une longue durée. Notre check-list de souscription récapitule tout ce qu'il faut vérifier." },
      { type: "faq", items: [
        { q: "Faut-il payer plus cher pour un bon service ?", a: "Pas nécessairement le plus cher, mais méfiez-vous du dérisoire. Un prix correct finance la stabilité ; les formules longues réduisent le coût mensuel." },
        { q: "Comment vérifier la qualité avant d'acheter ?", a: "Profitez d'une garantie ou d'un essai pour tester la stabilité aux heures de pointe et la qualité 4K sur votre propre écran." },
        { q: "Quelle durée d'abonnement choisir ?", a: "Commencez court pour évaluer le service, puis passez sur une formule longue (moins chère au mois) une fois convaincu." },
        { q: "Un prix très bas est-il forcément mauvais signe ?", a: "Un tarif anormalement bas pour un catalogue « illimité » doit alerter : la stabilité et le support ont un coût. Le trop beau pour être vrai l'est rarement." },
      ]},
      { type: "callout", title: "À retenir", items: [
        "Jugez sur des critères objectifs, pas sur le seul prix.",
        "La stabilité aux heures de pointe prime sur la taille de la liste.",
        "Exigez support, garantie et absence d'engagement.",
        "Testez la qualité réelle avant de vous engager longtemps.",
      ]},
    ],
  },
  {
    slug: "installer-iptv-sur-fire-tv-stick",
    title: "Installer l'IPTV sur Fire TV Stick : le guide complet",
    excerpt:
      "Le Fire TV Stick est l'un des moyens les plus simples de profiter de l'IPTV sur n'importe quel téléviseur. Voici comment le configurer étape par étape.",
    category: "Tutoriel",
    date: "2026-07-28",
    readingMinutes: 5,
    links: [
      { label: "Fire TV Stick", href: "/appareils/firestick" },
      { label: "Comment installer l'IPTV (guide général)", href: "/blog/comment-installer-iptv" },
      { label: "IPTV Smarters", href: "/applications/smarters" },
      { label: "Utiliser les codes Xtream", href: "/blog/comment-utiliser-les-codes-xtream" },
    ],
    body: [
      { type: "p", text: "Le Fire TV Stick d'Amazon transforme n'importe quelle télévision avec une prise HDMI en Smart TV, pour un budget réduit. C'est l'un des moyens les plus simples et les plus populaires de profiter de l'IPTV. Voici le guide complet, étape par étape, avec les points spécifiques au Fire TV que les guides génériques oublient souvent." },
      { type: "h2", text: "Étape 1 : préparer l'appareil" },
      { type: "p", text: "Branchez le Fire TV Stick sur une prise HDMI, alimentez-le de préférence via une prise secteur (le port USB de la TV est souvent trop faible), connectez-le à votre Wi-Fi et installez la mise à jour du système si elle est proposée." },
      { type: "h2", text: "Étape 2 : installer une application IPTV" },
      { type: "p", text: "Depuis l'Amazon Appstore, installez une application compatible comme IPTV Smarters Pro : cherchez-la, sélectionnez « Obtenir » et attendez l'installation. Certaines applications non présentes dans le store passent par l'outil Downloader — mais pour débuter, l'Appstore suffit largement." },
      { type: "h2", text: "Étape 3 : ajouter vos accès" },
      { type: "p", text: "Ouvrez l'application, choisissez l'ajout via Xtream Codes API (recommandé) ou lien M3U, puis saisissez les identifiants reçus par e-mail après votre commande. Prenez votre temps : la saisie à la télécommande est la principale source d'erreurs." },
      { type: "h2", text: "La procédure en résumé" },
      { type: "ol", items: [
        "Branchez et alimentez le Fire TV Stick, connectez-le au Wi-Fi.",
        "Mettez le système à jour si nécessaire.",
        "Installez IPTV Smarters depuis l'Amazon Appstore.",
        "Ajoutez vos accès (Xtream Codes ou M3U) reçus par e-mail.",
        "Patientez le temps du premier chargement des chaînes.",
      ]},
      { type: "h2", text: "Si ça ne fonctionne pas" },
      { type: "p", text: "Un Fire TV Stick à la mémoire saturée ralentit : n'installez que le nécessaire et redémarrez-le de temps en temps. En cas de coupures, préférez le modèle 4K et rapprochez-le du routeur, ou passez par un adaptateur Ethernet." },
      { type: "faq", items: [
        { q: "Quel Fire TV Stick choisir pour l'IPTV ?", a: "La version 4K est recommandée pour un écran Ultra HD et offre plus de puissance. Le modèle standard convient pour un écran Full HD." },
        { q: "Faut-il l'outil Downloader ?", a: "Seulement pour installer une application absente de l'Amazon Appstore. Pour IPTV Smarters, disponible dans le store, ce n'est pas nécessaire." },
        { q: "Mon Fire TV Stick rame, que faire ?", a: "Sa mémoire est limitée : désinstallez les applications inutiles, redémarrez-le régulièrement et évitez d'en installer trop en parallèle." },
      ]},
      { type: "callout", title: "À retenir", items: [
        "Le Fire TV Stick 4K est un point d'entrée simple et abordable.",
        "Alimentez-le par une prise secteur, pas par l'USB de la TV.",
        "IPTV Smarters s'installe directement depuis l'Amazon Appstore.",
        "Saisissez vos accès sans erreur : c'est la cause n°1 des échecs.",
      ]},
    ],
  },
  {
    slug: "iptv-et-vpn-faut-il-en-utiliser-un",
    title: "IPTV et VPN : faut-il en utiliser un ?",
    excerpt:
      "Le VPN est souvent recommandé avec l'IPTV. À quoi sert-il vraiment, et comment le choisir sans dégrader la qualité de streaming ?",
    category: "Conseils",
    date: "2026-07-05",
    readingMinutes: 7,
    links: [
      { label: "Comment configurer un VPN pour l'IPTV", href: "/blog/comment-configurer-un-vpn-pour-iptv" },
      { label: "IPTV et protection de la vie privée", href: "/blog/iptv-et-protection-de-la-vie-privee" },
      { label: "IPTV bloqué par l'opérateur", href: "/problemes/iptv-bloque-operateur" },
      { label: "L'IPTV est-il légal en France", href: "/blog/iptv-legal-en-france" },
    ],
    body: [
      { type: "p", text: "« Utilise un VPN avec l'IPTV », lit-on partout. Mais est-ce vraiment nécessaire, ou est-ce un réflexe marketing ? La vérité est nuancée : un VPN a de réels avantages, mais aussi des limites qu'on vous cache souvent. Ce guide sépare le vrai du faux et vous aide à décider si vous en avez besoin — puis à bien le choisir si oui." },
      { type: "h2", text: "À quoi sert vraiment un VPN ?" },
      { type: "p", text: "Un VPN (réseau privé virtuel) fait deux choses : il chiffre votre trafic internet, de sorte que votre fournisseur d'accès ne voit plus le détail de ce que vous faites, et il masque votre adresse IP derrière celle d'un serveur ailleurs. C'est un outil de confidentialité, avant tout." },
      { type: "h2", text: "Les vraies raisons d'en utiliser un avec l'IPTV" },
      { type: "ul", items: [
        "La confidentialité : votre opérateur ne voit plus le détail de votre trafic.",
        "Contourner un bridage : si votre fournisseur ralentit les flux vidéo le soir, un VPN peut rétablir la fluidité.",
        "L'usage à l'étranger : accéder à vos contenus habituels en voyage, malgré des filtrages locaux.",
      ]},
      { type: "h2", text: "Ce qu'un VPN ne fait PAS" },
      { type: "p", text: "C'est là que beaucoup se trompent. Un VPN ne rend pas légal un contenu qui ne l'est pas — il protège la vie privée, pas le droit (voir notre article sur la légalité). Il n'améliore pas non plus votre débit : au mieux il n'y touche pas, au pire il le réduit un peu à cause du chiffrement. Et il n'est pas indispensable : si tout fonctionne bien et que la confidentialité n'est pas une priorité pour vous, vous pouvez vous en passer." },
      { type: "h2", text: "Alors, faut-il en utiliser un ? Le verdict" },
      { type: "table", headers: ["Votre situation", "VPN recommandé ?"], rows: [
        ["Votre opérateur bride les flux le soir", "Oui, c'est le cas le plus utile"],
        ["La confidentialité vous tient à cœur", "Oui"],
        ["Vous regardez souvent à l'étranger", "Oui, selon les cas"],
        ["Tout est fluide et la vie privée vous importe peu", "Optionnel"],
      ]},
      { type: "h2", text: "Bien choisir un VPN pour le streaming" },
      { type: "p", text: "Tous les VPN ne se valent pas pour la vidéo. Pour éviter les ralentissements, privilégiez un service rapide, doté de serveurs proches de la France, d'un protocole moderne (WireGuard) et d'une politique de non-conservation des journaux. La vitesse et la stabilité comptent plus que le nombre de pays affichés. 4kiptvfr.com est par ailleurs 100 % compatible avec les VPN." },
      { type: "h2", text: "Comment le mettre en place" },
      { type: "p", text: "Une fois le VPN choisi, l'installer prend quelques minutes, sur l'appareil ou sur le routeur pour couvrir tout le foyer. Notre tutoriel pas à pas détaille chaque étape." },
      { type: "faq", items: [
        { q: "Le VPN ralentit-il l'IPTV ?", a: "Un peu, à cause du chiffrement. Avec un VPN rapide et un serveur proche, la perte est minime et souvent invisible. Un serveur lointain, en revanche, peut dégrader la fluidité." },
        { q: "Un VPN gratuit suffit-il ?", a: "Rarement pour le streaming : débit bridé, serveurs saturés, et parfois revente de données. Pour l'IPTV, un VPN payant rapide est bien plus adapté." },
        { q: "Le VPN est-il obligatoire pour l'IPTV ?", a: "Non. Il est utile pour la confidentialité et pour contourner un bridage, mais l'IPTV fonctionne sans." },
        { q: "Un VPN me rend-il totalement anonyme ?", a: "Il renforce fortement la confidentialité mais aucun outil ne garantit l'anonymat absolu. C'est une protection, pas une invisibilité totale." },
      ]},
      { type: "callout", title: "À retenir", items: [
        "Le VPN sert la confidentialité et contourne un éventuel bridage.",
        "Il ne rend rien légal et n'améliore pas le débit.",
        "Il n'est pas obligatoire : à vous de peser confidentialité et confort.",
        "Choisissez-le rapide, avec des serveurs proches, pour ne pas ralentir le flux.",
      ]},
    ],
  },
  {
    slug: "quest-ce-que-liptv",
    title: "Qu'est-ce que l'IPTV ? Le guide complet pour débuter",
    excerpt:
      "IPTV, M3U, Xtream Codes, EPG… On vous explique simplement ce qu'est l'IPTV, comment ça marche, ce qu'il faut pour commencer et en quoi c'est différent d'une box classique.",
    category: "Guide",
    date: "2026-08-30",
    readingMinutes: 10,
    links: [
      { label: "Comment installer l'IPTV", href: "/blog/comment-installer-iptv" },
      { label: "Quelle connexion internet pour l'IPTV", href: "/blog/quel-forfait-internet-pour-iptv" },
      { label: "IPTV, OTT, VOD : les différences", href: "/blog/difference-entre-iptv-ott-et-vod" },
      { label: "L'IPTV est-il légal en France ?", href: "/blog/iptv-legal-en-france" },
      { label: "Comment choisir son abonnement", href: "/blog/comment-choisir-son-abonnement-iptv" },
    ],
    body: [
      { type: "p", text: "Vous entendez parler d'« IPTV » partout — chez un proche, sur un forum, dans une pub — sans vraiment savoir de quoi il s'agit ni si c'est fait pour vous ? Ce guide répond à tout, sans jargon : ce qu'est l'IPTV, comment elle fonctionne, ce qu'il faut pour commencer, en quoi elle diffère d'une box ou du satellite, et les questions de légalité. À la fin, vous saurez si l'IPTV correspond à votre besoin et par où débuter." },
      { type: "h2", text: "IPTV : la définition en une phrase" },
      { type: "p", text: "IPTV signifie « Internet Protocol Television ». C'est la télévision acheminée par votre connexion internet, au lieu des ondes hertziennes, du câble ou du satellite. Là où il fallait une antenne ou une parabole, c'est désormais votre box internet qui fait arriver les chaînes jusqu'à l'écran." },
      { type: "h2", text: "Comment fonctionne l'IPTV, étape par étape" },
      { type: "p", text: "Le principe est plus simple qu'il n'y paraît. Un serveur met à disposition des flux vidéo. Votre application — le « lecteur » — s'y connecte grâce à des identifiants et affiche le tout sous forme de chaînes et de catégories, comme le menu d'une télévision classique." },
      { type: "ol", items: [
        "Vous ouvrez le lecteur et sélectionnez une chaîne.",
        "Le lecteur demande le flux correspondant au serveur.",
        "Le serveur envoie la vidéo, découpée en petits segments successifs.",
        "Le lecteur constitue une courte réserve (le buffer) puis lance la lecture.",
      ]},
      { type: "p", text: "Ce fonctionnement par segments explique le léger délai au démarrage d'une chaîne, et le fait qu'une bonne connexion soit déterminante pour la fluidité." },
      { type: "h2", text: "IPTV, OTT, VOD : ne pas confondre" },
      { type: "p", text: "Ces sigles se recoupent mais ne sont pas synonymes. L'IPTV désigne la télévision par internet (surtout le direct). L'OTT désigne tout contenu diffusé « par-dessus » le réseau, indépendamment de l'opérateur. La VOD, elle, est la vidéo à la demande. Nous détaillons ces nuances dans un article dédié." },
      { type: "h2", text: "De quoi a-t-on besoin pour commencer ?" },
      { type: "p", text: "Quatre éléments suffisent, et vous en possédez probablement déjà la plupart :" },
      { type: "table", headers: ["Élément", "Ce que c'est", "Ce qu'il faut savoir"], rows: [
        ["Une connexion", "Votre accès internet", "Une ligne stable suffit ; la fibre est idéale pour la 4K"],
        ["Un appareil", "Smart TV, boîtier, clé, mobile ou PC", "La plupart des écrans récents conviennent"],
        ["Un lecteur", "L'application qui affiche les chaînes", "Gratuit (IPTV Smarters, VLC…)"],
        ["Un abonnement", "Qui fournit vos identifiants d'accès", "Reçus par e-mail après la commande"],
      ]},
      { type: "h2", text: "M3U, Xtream Codes, EPG : le vocabulaire essentiel" },
      { type: "p", text: "Trois termes reviennent sans cesse. Le fichier M3U est une liste de chaînes que le lecteur sait lire — un sommaire, en somme. Les codes Xtream (Xtream Codes API) sont l'autre méthode de connexion : une URL, un identifiant et un mot de passe, qui chargent en plus les catégories et le guide. L'EPG, enfin, est ce guide des programmes qui indique ce qui passe maintenant et ensuite." },
      { type: "h2", text: "En quoi l'IPTV diffère d'une box opérateur ou du satellite" },
      { type: "p", text: "Une box d'opérateur ou une parabole imposent un bouquet fixe, un matériel dédié et souvent un engagement. L'IPTV renverse la logique :" },
      { type: "table", headers: ["Critère", "IPTV", "Box / satellite classique"], rows: [
        ["Matériel", "Vos appareils actuels", "Décodeur ou parabole dédiés"],
        ["Catalogue", "Très large, international", "Bouquet défini"],
        ["Engagement", "Souvent aucun", "12–24 mois fréquents"],
        ["Mobilité", "Partout avec internet", "Lié au domicile"],
      ]},
      { type: "h2", text: "L'IPTV est-elle légale ?" },
      { type: "p", text: "La technologie IPTV est parfaitement légale — c'est un simple moyen de diffuser la télévision. Ce qui fait la différence, ce sont les droits sur les contenus proposés. Nous consacrons un article entier à cette question, à lire avant de choisir un service." },
      { type: "h2", text: "Par où commencer" },
      { type: "p", text: "Pour débuter, la marche à suivre est toujours la même : choisir un appareil, installer un lecteur, saisir vos identifiants, regarder. Notre guide d'installation détaille chaque étape selon votre matériel." },
      { type: "faq", items: [
        { q: "L'IPTV remplace-t-elle ma box internet ?", a: "Non : l'IPTV utilise votre connexion internet, elle ne la remplace pas. Vous gardez votre box ; l'IPTV vient s'ajouter par-dessus." },
        { q: "Quelle est la différence avec Netflix ou une plateforme de streaming ?", a: "Les plateformes proposent surtout des films et séries à la demande. L'IPTV ajoute la télévision en direct — chaînes françaises, sport, international — en plus d'une vidéothèque." },
        { q: "L'IPTV fonctionne-t-elle sur une télévision ancienne ?", a: "Oui, en y branchant une clé (Fire TV Stick) ou un boîtier Android TV. La télé ne sert alors que d'écran." },
        { q: "Faut-il obligatoirement la fibre ?", a: "Non. Une connexion stable en ADSL suffit pour la HD ; la fibre devient utile pour la 4K et le multi-écrans." },
      ]},
      { type: "callout", title: "À retenir", items: [
        "L'IPTV, c'est la télévision par internet, sans antenne ni parabole.",
        "Il faut une connexion stable, un appareil, un lecteur et un abonnement.",
        "M3U et Xtream Codes sont deux façons de se connecter ; l'EPG est le guide des programmes.",
        "La technologie est légale ; tout dépend des droits sur les contenus.",
        "On démarre en quatre étapes : appareil, lecteur, identifiants, lecture.",
      ]},
    ],
  },
  {
    slug: "iptv-legal-en-france",
    title: "L'IPTV est-il légal en France ?",
    excerpt:
      "La question revient sans cesse. On fait le point clairement : ce qui est légal, ce qui ne l'est pas, et comment reconnaître un service qui respecte les règles.",
    category: "Conseils",
    date: "2026-08-25",
    readingMinutes: 7,
    links: [
      { label: "Reconnaître une arnaque IPTV", href: "/blog/reconnaitre-arnaque-iptv" },
      { label: "IPTV et VPN : faut-il en utiliser un", href: "/blog/iptv-et-vpn-faut-il-en-utiliser-un" },
      { label: "Comment choisir son abonnement", href: "/blog/comment-choisir-son-abonnement-iptv" },
      { label: "Foire aux questions", href: "/faq" },
    ],
    body: [
      { type: "p", text: "« L'IPTV, c'est légal ou pas ? » C'est sans doute la question la plus posée avant de se lancer, et la réponse mérite mieux qu'un oui ou un non. Cet article fait le point calmement : ce que dit le bon sens juridique, la différence essentielle entre la technologie et les contenus, votre responsabilité en tant que spectateur, et comment reconnaître un service qui joue le jeu. Précision utile d'emblée : ce guide est informatif et ne remplace pas l'avis d'un professionnel du droit." },
      { type: "h2", text: "La technologie IPTV est parfaitement légale" },
      { type: "p", text: "Commençons par lever le principal malentendu : l'IPTV n'est qu'une méthode de diffusion — de la télévision acheminée par internet. En soi, elle est aussi légale que le câble ou le satellite. D'ailleurs, de grands opérateurs et des services officiels s'en servent tous les jours. Le mot « IPTV » ne désigne donc rien d'illégal par nature." },
      { type: "h2", text: "La vraie question : les droits sur les contenus" },
      { type: "p", text: "Ce qui détermine la légalité, ce ne sont pas les tuyaux, mais ce qui passe dedans. Diffuser une chaîne ou un film suppose d'en détenir les droits, négociés avec les ayants droit. Un service qui propose des contenus dont il possède les droits agit dans les règles ; un service qui rediffuse des contenus protégés sans autorisation, non." },
      { type: "h2", text: "Ce qui est autorisé, ce qui ne l'est pas" },
      { type: "table", headers: ["Situation", "Statut"], rows: [
        ["Regarder des contenus dont le service détient les droits", "Légal"],
        ["Utiliser une offre officielle et transparente", "Légal"],
        ["Rediffuser ou revendre des contenus protégés sans droits", "Illégal"],
        ["Proposer un catalogue « illimité » sans aucun ayant droit", "Illégal"],
      ]},
      { type: "h2", text: "Et vous, spectateur : quelle responsabilité ?" },
      { type: "p", text: "La loi distingue nettement celui qui diffuse sans droits (l'exposition la plus lourde) de celui qui regarde. Pour autant, l'utilisateur n'est pas totalement à l'abri de tout risque, et le cadre évolue. La prudence consiste donc à privilégier des services transparents et à se méfier de tout ce qui paraît trop beau pour être vrai. En cas de doute sérieux, seul un juriste pourra vous répondre pour votre situation précise." },
      { type: "h2", text: "Comment reconnaître un service qui respecte les règles" },
      { type: "ul", items: [
        "Des conditions d'utilisation claires et une identité vérifiable.",
        "Un vrai support, joignable et identifiable.",
        "Des promesses réalistes, sans « tout, partout, pour trois euros ».",
        "Une réputation cohérente en dehors de son propre site.",
      ]},
      { type: "p", text: "Ces critères recoupent ceux d'un service fiable ; nous les détaillons dans notre guide pour reconnaître une arnaque IPTV." },
      { type: "h2", text: "Un VPN rend-il l'IPTV « légale » ?" },
      { type: "p", text: "Non, et c'est un point important. Un VPN protège votre vie privée et chiffre votre connexion, mais il ne transforme pas un usage illégal en usage légal. Son intérêt est ailleurs — la confidentialité — comme nous l'expliquons dans notre article dédié au VPN." },
      { type: "faq", items: [
        { q: "Est-il illégal de simplement regarder l'IPTV ?", a: "La technologie et le fait de regarder des contenus autorisés sont légaux. Le problème se pose avec des contenus rediffusés sans droits ; la responsabilité la plus lourde pèse sur celui qui diffuse, mais mieux vaut rester prudent et bien choisir son service." },
        { q: "Un VPN me met-il à l'abri juridiquement ?", a: "Non. Un VPN protège votre vie privée mais ne rend pas légal un contenu qui ne l'est pas. Ne le confondez pas avec une protection juridique." },
        { q: "Comment savoir si un service est en règle ?", a: "Regardez sa transparence : identité, conditions, support, promesses réalistes. Un service opaque au prix dérisoire doit alerter." },
        { q: "Ce risque évolue-t-il ?", a: "Oui, le cadre juridique et les contrôles évoluent régulièrement. C'est une raison de plus pour privilégier des services sérieux et transparents." },
      ]},
      { type: "callout", title: "À retenir", items: [
        "La technologie IPTV est légale ; tout dépend des droits sur les contenus.",
        "La responsabilité la plus lourde vise celui qui diffuse sans droits.",
        "Un VPN protège la vie privée, il ne rend rien légal.",
        "Privilégiez les services transparents et méfiez-vous des offres irréalistes.",
        "Cet article est informatif et ne constitue pas un conseil juridique.",
      ]},
    ],
  },
  {
    slug: "iptv-4k-materiel-et-conditions",
    title: "IPTV en 4K : quel matériel et quelles conditions ?",
    excerpt:
      "La 4K change tout côté image, mais elle a des exigences. Voici ce qu'il faut vraiment — débit, appareil, écran — pour en profiter sans coupure.",
    category: "Guide",
    date: "2026-08-20",
    readingMinutes: 8,
    links: [
      { label: "Comprendre 4K, HDR et H.265", href: "/blog/comprendre-4k-hdr-h265" },
      { label: "Quelle connexion internet pour l'IPTV", href: "/blog/quel-forfait-internet-pour-iptv" },
      { label: "Améliorer la qualité d'image", href: "/blog/comment-ameliorer-la-qualite-dimage-iptv" },
      { label: "Offre 4K", href: "/abonnement/4k" },
    ],
    body: [
      { type: "p", text: "Vous avez une belle TV 4K et vous voulez que votre IPTV soit à la hauteur ? La 4K offre quatre fois plus de détails que la Full HD, mais elle ne s'improvise pas : il faut une chaîne de matériel entièrement compatible, du serveur jusqu'à l'écran. Voici la check-list complète des conditions à réunir — et comment vérifier chacune. (Ce qu'est réellement la 4K, le HDR et le H.265, nous l'expliquons dans un guide dédié.)" },
      { type: "h2", text: "Les quatre conditions d'une vraie 4K" },
      { type: "p", text: "Pour afficher une image 4K, chaque maillon doit suivre : le contenu doit exister en 4K, la connexion doit tenir le débit, l'appareil doit décoder le flux, et l'écran doit être en Ultra HD. Il suffit qu'un maillon manque pour retomber en Full HD." },
      { type: "table", headers: ["Condition", "Ce qu'il faut", "Comment vérifier"], rows: [
        ["Le contenu", "Une chaîne disponible en 4K", "Repérer la mention 4K/UHD dans la liste"],
        ["La connexion", "~25 Mb/s stables par flux", "Faire un test de débit"],
        ["L'appareil", "Décodage 4K + codec H.265 (HEVC)", "Vérifier la fiche de l'appareil"],
        ["L'écran", "Dalle 4K (3840 × 2160)", "Consulter les caractéristiques du téléviseur"],
      ]},
      { type: "h2", text: "Un appareil qui décode la 4K et le H.265" },
      { type: "p", text: "C'est le point le plus souvent négligé. L'appareil doit décoder à la fois la résolution 4K et le codec H.265 (HEVC), celui qui rend le streaming 4K possible sans saturer la connexion. Les matériels suivants le font sans peine :" },
      { type: "ul", items: [
        "Smart TV 4K récentes (Samsung, LG, Sony, Philips, TCL…)",
        "Fire TV Stick 4K et 4K Max",
        "Apple TV 4K",
        "Boîtiers Android TV haut de gamme comme la Nvidia Shield",
      ]},
      { type: "p", text: "Un vieux boîtier ou une clé d'entrée de gamme, eux, plafonnent souvent en Full HD, même reliés à une TV 4K." },
      { type: "h2", text: "Une connexion à la hauteur" },
      { type: "p", text: "La 4K demande environ 25 Mb/s stables par flux. Ce n'est pas qu'une question de vitesse maximale : la régularité prime, sinon le lecteur bascule automatiquement en définition inférieure. La fibre en Ethernet reste le duo idéal ; voyez notre guide sur la connexion pour dimensionner la vôtre." },
      { type: "h2", text: "Un écran réellement 4K (et bien réglé)" },
      { type: "p", text: "Enfin, l'écran doit posséder une dalle 4K. Sur un téléviseur Full HD, un flux 4K s'affiche en Full HD : l'image reste bonne, mais sans le gain de netteté attendu. Pensez aussi à utiliser un câble HDMI récent et à désactiver les modes « éco » qui brident l'image — des détails que nous approfondissons dans notre guide sur la qualité d'image." },
      { type: "faq", items: [
        { q: "Ma TV est 4K, mais l'image ne semble pas en 4K, pourquoi ?", a: "Le plus souvent, l'appareil de lecture (clé ou boîtier) ne décode pas la 4K, la chaîne n'existe pas en 4K, ou le débit est insuffisant et le lecteur a réduit la définition." },
        { q: "Le Fire TV Stick standard suffit-il pour la 4K ?", a: "Non : il faut la version 4K (ou 4K Max). Le modèle de base est limité à la Full HD." },
        { q: "Toutes les chaînes sont-elles disponibles en 4K ?", a: "Non. La 4K concerne surtout certaines chaînes de cinéma, de sport et de démonstration. La majorité des chaînes restent diffusées en HD ou Full HD." },
        { q: "Vaut-il mieux une 4K instable ou une Full HD fluide ?", a: "La Full HD fluide, sans hésiter. Une 4K qui coupe est bien moins agréable qu'une Full HD stable, surtout sur le sport." },
      ]},
      { type: "callout", title: "À retenir", items: [
        "La 4K exige que TOUS les maillons suivent : contenu, connexion, appareil, écran.",
        "L'appareil doit décoder la 4K ET le H.265 (HEVC).",
        "Comptez ~25 Mb/s stables par flux 4K.",
        "En cas de débit limité, la Full HD reste excellente et plus stable.",
      ]},
    ],
  },
  {
    slug: "comment-installer-iptv",
    title: "Comment installer l'IPTV : le guide général",
    excerpt:
      "Smart TV, boîtier, clé, mobile : la marche à suivre est toujours la même en quatre étapes. Voici la méthode, avec les liens vers chaque appareil.",
    category: "Tutoriel",
    date: "2026-08-18",
    readingMinutes: 8,
    links: [
      { label: "M3U ou Xtream Codes : que choisir", href: "/blog/m3u-ou-xtream-codes" },
      { label: "Toutes les applications IPTV", href: "/applications" },
      { label: "Installer sur Samsung", href: "/appareils/samsung" },
      { label: "Installer sur Fire TV Stick", href: "/appareils/firestick" },
      { label: "Tous les appareils", href: "/appareils" },
    ],
    body: [
      { type: "p", text: "Vous venez de recevoir vos accès et vous ne savez pas par où commencer ? Bonne nouvelle : quel que soit l'appareil, l'installation suit toujours la même logique en quatre étapes. Ce guide vous donne la méthode universelle, valable partout, puis vous oriente vers le tutoriel précis de votre matériel. Une fois le principe compris, vous saurez configurer n'importe quel écran en quelques minutes." },
      { type: "h2", text: "Avant de commencer : ce qu'il vous faut" },
      { type: "p", text: "Réunissez trois choses : l'appareil sur lequel vous voulez regarder, une connexion internet active, et l'e-mail d'activation reçu après la commande — c'est lui qui contient vos identifiants. Gardez-le ouvert à côté de vous : vous allez recopier ces informations." },
      { type: "h2", text: "Étape 1 : choisir et préparer l'appareil" },
      { type: "p", text: "Smart TV, boîtier Android TV, Fire TV Stick, smartphone ou ordinateur : tous conviennent. Le plus simple reste d'utiliser directement votre téléviseur s'il est connecté à internet. S'il ne l'est pas ou s'il rame, une petite clé ou un boîtier branché en HDMI fait parfaitement l'affaire." },
      { type: "h2", text: "Étape 2 : installer un lecteur" },
      { type: "p", text: "Le lecteur est l'application qui affiche vos chaînes. On l'installe depuis le magasin de l'appareil :" },
      { type: "table", headers: ["Appareil", "Où installer le lecteur", "Lecteur conseillé"], rows: [
        ["Smart TV Samsung / LG", "Store intégré (Samsung Apps, LG Content Store)", "Lecteur compatible ou app à portail"],
        ["Android TV / boîtier", "Google Play", "IPTV Smarters, TiviMate"],
        ["Fire TV Stick", "Amazon Appstore", "IPTV Smarters"],
        ["Mobile / tablette", "App Store, Google Play", "IPTV Smarters"],
        ["Ordinateur", "Site de l'éditeur", "VLC, IPTV Smarters"],
      ]},
      { type: "h2", text: "Étape 3 : ajouter vos identifiants (Xtream ou M3U)" },
      { type: "p", text: "Ouvrez le lecteur et ajoutez vos accès. Deux méthodes existent : les codes Xtream (une URL de serveur, un identifiant, un mot de passe) ou un lien M3U. Quand le lecteur propose Xtream, préférez-le : il charge automatiquement les catégories et le guide des programmes. Recopiez les informations exactement, sans espace superflu. Pour choisir entre les deux, voyez notre comparatif M3U ou Xtream." },
      { type: "h2", text: "Étape 4 : premier lancement" },
      { type: "p", text: "La liste des chaînes se charge, le guide des programmes se remplit progressivement, et vous pouvez commencer à regarder. Prenez deux minutes pour mettre vos chaînes préférées en favoris : vous les retrouverez ensuite d'un geste, sans faire défiler des milliers d'entrées." },
      { type: "h2", text: "Les erreurs d'installation les plus fréquentes" },
      { type: "ul", items: [
        "Un espace ou un caractère en trop dans l'URL ou les identifiants : la connexion échoue.",
        "Avoir choisi « M3U » alors qu'on colle des codes Xtream (ou l'inverse).",
        "Un abonnement pas encore activé : patientez que l'e-mail arrive.",
        "Une application ancienne : mettez le lecteur à jour si rien ne se charge.",
      ]},
      { type: "h2", text: "Le guide précis de votre appareil" },
      { type: "p", text: "Chaque matériel a ses subtilités (nom du store, réglages). Retrouvez le tutoriel dédié à votre appareil sur nos pages Samsung, LG, Fire TV Stick, Android TV, Apple TV ou ordinateur, accessibles depuis la rubrique Appareils." },
      { type: "faq", items: [
        { q: "Combien de temps prend l'installation ?", a: "Quelques minutes : le plus long est d'installer le lecteur. La saisie des identifiants et le chargement de la liste prennent moins d'une minute." },
        { q: "Puis-je installer l'IPTV sur plusieurs appareils ?", a: "Oui, autant que vous voulez. Ce qui est limité, c'est le nombre d'écrans qui regardent en même temps (les connexions simultanées)." },
        { q: "Aucune chaîne n'apparaît après l'installation, que faire ?", a: "Vérifiez la méthode (Xtream vs M3U), l'exactitude de l'URL et des identifiants, puis votre connexion. Neuf fois sur dix, c'est une faute de saisie." },
        { q: "Faut-il tout réinstaller à chaque renouvellement ?", a: "Non. Après un renouvellement, vos réglages et favoris sont conservés : il suffit de rouvrir l'application." },
      ]},
      { type: "callout", title: "À retenir", items: [
        "La méthode est la même partout : appareil, lecteur, identifiants, lecture.",
        "Préférez les codes Xtream quand ils sont proposés (catégories + EPG automatiques).",
        "Recopiez vos identifiants sans espace superflu — c'est l'erreur n°1.",
        "Chaque appareil a son tutoriel détaillé dans la rubrique Appareils.",
      ]},
    ],
  },
  {
    slug: "reconnaitre-arnaque-iptv",
    title: "Comment reconnaître une arnaque IPTV et l'éviter",
    excerpt:
      "Prix trop bas, promesses irréalistes, paiement douteux : voici les signaux d'alerte d'un service IPTV à fuir, et les critères d'un service fiable.",
    category: "Conseils",
    date: "2026-08-15",
    readingMinutes: 7,
    links: [
      { label: "Comment choisir son abonnement", href: "/blog/comment-choisir-son-abonnement-iptv" },
      { label: "L'IPTV est-il légal en France", href: "/blog/iptv-legal-en-france" },
      { label: "Check-list avant de souscrire", href: "/blog/checklist-avant-de-souscrire-un-abonnement-iptv" },
    ],
    body: [
      { type: "p", text: "Une offre à 15 € l'année pour « toutes les chaînes du monde en 4K » vous fait de l'œil ? Prudence : le marché de l'IPTV attire aussi des arnaqueurs, et certaines offres sont conçues pour encaisser puis disparaître. Ce guide vous apprend à repérer les pièges avant de payer, à identifier les arnaques les plus fréquentes, et à réagir si vous êtes déjà tombé dedans." },
      { type: "h2", text: "Les signaux d'alerte qui doivent vous arrêter" },
      { type: "ul", items: [
        "Un prix dérisoire, très en dessous du marché, pour un catalogue « illimité ».",
        "Aucune information de contact ni support identifiable.",
        "Des promesses impossibles : « 100 % des chaînes du monde, zéro coupure garantie ».",
        "Uniquement des moyens de paiement non traçables, sans aucune garantie.",
        "Une pression à payer vite, « avant la fin de la promo ».",
        "Des avis exclusivement dithyrambiques, tous datés du même moment.",
      ]},
      { type: "h2", text: "Les arnaques les plus courantes" },
      { type: "h3", text: "Le service fantôme" },
      { type: "p", text: "Vous payez, vous ne recevez jamais vos accès — ou ils cessent de fonctionner au bout de quelques jours, et le vendeur devient injoignable. C'est l'arnaque la plus fréquente, favorisée par des paiements sans recours." },
      { type: "h3", text: "Le catalogue gonflé" },
      { type: "p", text: "L'offre annonce des dizaines de milliers de chaînes, mais une grande partie des liens sont morts. La liste impressionne, l'usage déçoit. Un vrai test avant engagement révèle vite le problème." },
      { type: "h3", text: "Le faux « essai gratuit »" },
      { type: "p", text: "Un « essai gratuit » qui réclame votre carte bancaire dès le départ cache souvent un prélèvement automatique. Lisez toujours ce que vous signez avant de saisir vos coordonnées." },
      { type: "h2", text: "Attention au moyen de paiement" },
      { type: "p", text: "Le mode de paiement change votre niveau de protection. Une carte bancaire via un processeur reconnu offre un recours en cas de problème. Un virement ou un envoi de cryptomonnaie directement à un inconnu, à l'inverse, est quasi irréversible : en cas d'arnaque, vous n'avez presque aucun moyen de récupérer votre argent. Le paiement en crypto n'est pas un signe d'arnaque en soi, mais méfiez-vous s'il est le seul proposé, sans aucune autre garantie." },
      { type: "h2", text: "Comment acheter en sécurité" },
      { type: "ul", items: [
        "Privilégiez un service transparent, avec une identité et des conditions claires.",
        "Exigez une garantie ou un essai pour tester avant l'engagement.",
        "Cherchez des avis en dehors du site du vendeur.",
        "Vérifiez qu'un vrai support répond avant de payer.",
        "Commencez par une courte durée avant de renouveler sur du long terme.",
      ]},
      { type: "h2", text: "Que faire si vous êtes déjà victime" },
      { type: "p", text: "Si vous avez payé par carte, contactez votre banque pour contester l'opération : un recours est souvent possible. Signalez le site sur les plateformes officielles de signalement. Enfin, si vous aviez réutilisé un mot de passe, changez-le partout où il servait — les données saisies peuvent avoir été collectées." },
      { type: "faq", items: [
        { q: "Un prix bas est-il toujours une arnaque ?", a: "Non, mais un tarif anormalement bas pour un catalogue « illimité » est le premier signal d'alerte. La stabilité et le support ont un coût que le dérisoire ne couvre pas." },
        { q: "Payer en cryptomonnaie est-il risqué ?", a: "La crypto en elle-même n'est pas une arnaque, mais un envoi direct à un inconnu est irréversible. Méfiez-vous si c'est le seul mode de paiement, sans garantie." },
        { q: "Comment vérifier des avis fiables ?", a: "Cherchez des retours en dehors du site du vendeur, variés dans le temps et le ton. Une avalanche d'avis cinq étoiles identiques doit éveiller les soupçons." },
        { q: "Le service a disparu après mon paiement, que faire ?", a: "Contestez le paiement auprès de votre banque si c'était par carte, signalez le site, et changez tout mot de passe que vous auriez réutilisé." },
      ]},
      { type: "callout", title: "À retenir", items: [
        "Un prix trop beau pour être vrai est le premier signal d'alerte.",
        "Le mode de paiement conditionne votre recours : la carte protège, l'envoi direct non.",
        "Testez avant de vous engager et cherchez des avis externes.",
        "Victime ? Contestez le paiement, signalez, changez vos mots de passe réutilisés.",
      ]},
    ],
  },
  {
    slug: "regarder-tv-francaise-etranger",
    title: "Regarder la télévision française à l'étranger",
    excerpt:
      "Expatrié ou en voyage, vous voulez garder vos chaînes françaises ? Voici comment l'IPTV permet de retrouver TF1, France TV et le sport, où que vous soyez.",
    category: "Guide",
    date: "2026-08-10",
    readingMinutes: 5,
    links: [
      { label: "Chaînes françaises", href: "/contenu/chaines/francaises" },
      { label: "IPTV et VPN", href: "/blog/iptv-et-vpn-faut-il-en-utiliser-un" },
      { label: "IPTV en famille", href: "/blog/iptv-multi-ecrans-famille" },
    ],
    body: [
      { type: "p", text: "Vous venez de vous installer à l'étranger, ou vous partez plusieurs mois, et vous découvrez que vos chaînes françaises ne répondent plus ? C'est le lot de tout expatrié : les services officiels de replay et de direct bloquent la diffusion hors de France. L'IPTV, elle, fonctionne partout où vous avez une connexion internet — voici pourquoi, et comment en profiter sereinement." },
      { type: "h2", text: "Pourquoi les chaînes françaises se bloquent à l'étranger" },
      { type: "p", text: "La plupart des plateformes de replay et de direct appliquent une restriction géographique : elles vérifient votre position via votre adresse IP et coupent l'accès hors du territoire. C'est frustrant quand on veut simplement suivre le JT, un match ou l'émission du soir depuis l'étranger." },
      { type: "h2", text: "Ce qui change une fois expatrié" },
      { type: "table", headers: ["Solution", "Depuis l'étranger", "Remarque"], rows: [
        ["Replay officiel (France TV, TF1…)", "Souvent bloqué", "Restriction géographique par IP"],
        ["TNT / satellite français", "Indisponible", "Hors zone de couverture"],
        ["IPTV", "Fonctionne", "Nécessite seulement internet"],
      ]},
      { type: "h2", text: "Comment l'IPTV résout le problème" },
      { type: "p", text: "Avec un abonnement IPTV, vos chaînes vous suivent : il suffit d'une connexion internet, sur place ou à l'hôtel, pour retrouver les chaînes françaises et internationales. Un VPN peut compléter le dispositif si votre connexion locale filtre certains flux — nous détaillons son usage dans un guide dédié." },
      { type: "ul", items: ["Retrouvez TF1, France 2/3, M6 et la TNT.", "Suivez le sport français malgré le décalage horaire.", "Gardez un lien avec l'actualité et les émissions du pays.", "Fonctionne sur Smart TV, mobile, tablette ou ordinateur."] },
      { type: "faq", items: [
        { q: "Pourquoi mon replay France TV ne marche plus à l'étranger ?", a: "Parce que ces services vérifient votre adresse IP et bloquent l'accès hors de France. L'IPTV, elle, ne dépend pas de cette restriction." },
        { q: "Ai-je besoin d'un VPN avec l'IPTV à l'étranger ?", a: "Pas toujours. L'IPTV fonctionne avec une simple connexion internet ; un VPN n'est utile que si votre réseau local filtre certains flux." },
        { q: "Cela fonctionne-t-il en voyage, à l'hôtel ?", a: "Oui, dès que vous disposez d'une connexion internet correcte, sur Smart TV, mobile, tablette ou ordinateur." },
      ]},
      { type: "callout", title: "À retenir", items: [
        "Les services français officiels se bloquent hors de France ; l'IPTV non.",
        "Il suffit d'une connexion internet, où que vous soyez.",
        "Un VPN aide si la connexion locale filtre les flux.",
        "Idéal pour les expatriés et les voyages prolongés.",
      ]},
    ],
  },
  {
    slug: "iptv-multi-ecrans-famille",
    title: "IPTV en famille : le multi-écrans expliqué",
    excerpt:
      "Regarder sur plusieurs télévisions en même temps, c'est possible — à condition de comprendre les connexions simultanées. On vous explique comment bien dimensionner.",
    category: "Guide",
    date: "2026-08-06",
    readingMinutes: 4,
    links: [
      { label: "Abonnement 2 connexions", href: "/abonnement/2-connexions" },
      { label: "Abonnement 3 connexions", href: "/abonnement/3-connexions" },
      { label: "Contrôle parental", href: "/blog/controle-parental-iptv" },
    ],
    body: [
      { type: "p", text: "Le sport au salon, un dessin animé dans la chambre, une série sur la tablette : dans un foyer, chacun a ses envies, souvent au même moment. L'IPTV le permet sans problème — mais un malentendu revient sans cesse au moment de choisir son offre : la différence entre le nombre d'appareils et le nombre de connexions simultanées. C'est le cœur de ce guide, car bien le comprendre évite de payer trop… ou pas assez." },
      { type: "h2", text: "Appareils installés ou connexions simultanées ?" },
      { type: "p", text: "C'est la distinction essentielle, et la source de presque toutes les confusions. Les deux notions n'ont rien à voir." },
      { type: "table", headers: ["Notion", "De quoi il s'agit", "Limité ?"], rows: [
        ["Appareils installés", "Les TV, mobiles, tablettes où l'app est configurée", "Non, autant que voulu"],
        ["Connexions simultanées", "Les flux joués en même temps", "Oui, selon votre offre"],
      ]},
      { type: "p", text: "Autrement dit, vous pouvez installer l'application sur cinq écrans avec une offre à deux connexions : simplement, deux d'entre eux au maximum pourront regarder en même temps." },
      { type: "h2", text: "Qu'est-ce qu'une connexion simultanée ?" },
      { type: "p", text: "Une connexion (ou « ligne ») correspond à un flux en cours de lecture. Avec une seule connexion, une seule chaîne peut être regardée à la fois. Pour deux écrans en même temps, il faut deux connexions, et ainsi de suite." },
      { type: "h2", text: "Combien en choisir ?" },
      { type: "ul", items: ["1 connexion : une seule télévision utilisée à la fois.", "2 connexions : salon + une chambre en simultané.", "3 connexions et plus : familles nombreuses ou plusieurs pièces équipées."] },
      { type: "faq", items: [
        { q: "Puis-je installer l'IPTV sur toutes les TV de la maison ?", a: "Oui, sans limite d'installations. Seul le nombre d'écrans qui regardent en même temps dépend de votre nombre de connexions." },
        { q: "Deux enfants peuvent-ils regarder deux dessins animés différents ?", a: "Oui, à condition d'avoir au moins deux connexions simultanées dans l'abonnement." },
        { q: "Comment savoir combien de connexions il me faut ?", a: "Comptez le maximum d'écrans susceptibles de fonctionner en même temps un soir type. C'est ce chiffre qui détermine votre offre." },
      ]},
      { type: "callout", title: "À retenir", items: [
        "Une connexion = un flux regardé en même temps.",
        "Comptez une connexion par écran utilisé simultanément.",
        "Vous pouvez installer l'application sur tous vos appareils.",
        "Choisissez le nombre de connexions selon les habitudes du foyer.",
      ]},
    ],
  },
  {
    slug: "mettre-a-jour-application-iptv",
    title: "Comment mettre à jour son application IPTV",
    excerpt:
      "Une application à jour, c'est moins de bugs et de meilleures performances. Voici comment mettre à jour votre lecteur selon l'appareil, et quand le faire.",
    category: "Tutoriel",
    date: "2026-08-02",
    readingMinutes: 4,
    links: [
      { label: "L'application plante", href: "/problemes/application-plante" },
      { label: "Toutes les applications", href: "/applications" },
      { label: "Meilleures applications IPTV", href: "/blog/meilleures-applications-iptv-2026" },
    ],
    body: [
      { type: "p", text: "Comme toute application, un lecteur IPTV s'améliore avec les mises à jour : corrections de bugs, meilleure stabilité, compatibilité avec les nouveaux appareils et les nouveaux formats. La maintenir à jour est l'un des gestes les plus simples pour éviter les plantages — et pourtant l'un des plus oubliés. Voici comment procéder selon votre appareil, et à quel moment le faire." },
      { type: "h2", text: "Où mettre à jour selon l'appareil" },
      { type: "table", headers: ["Appareil", "Où mettre à jour", "Mise à jour auto ?"], rows: [
        ["Smart TV Samsung", "Samsung Apps", "Souvent oui"],
        ["Smart TV LG", "LG Content Store", "Souvent oui"],
        ["Android TV / boîtier", "Google Play Store", "Configurable"],
        ["Fire TV Stick", "Amazon Appstore", "Configurable"],
        ["Mobile / tablette", "Play Store ou App Store", "Configurable"],
        ["Ordinateur", "Site officiel du lecteur", "Non (réinstaller)"],
      ]},
      { type: "h2", text: "Sur Smart TV et boîtiers" },
      { type: "p", text: "Ouvrez le store de l'appareil et vérifiez les mises à jour disponibles pour votre lecteur. Sur certains téléviseurs, elles s'installent automatiquement ; sur d'autres, il faut lancer la recherche à la main dans « Mes applications »." },
      { type: "h2", text: "Sur mobile et ordinateur" },
      { type: "p", text: "Sur smartphone et tablette, les mises à jour passent par le Play Store ou l'App Store — activez la mise à jour automatique pour ne plus y penser. Sur ordinateur, la plupart des lecteurs n'ont pas de store : réinstallez simplement la dernière version depuis le site officiel." },
      { type: "h2", text: "Quand faut-il mettre à jour ?" },
      { type: "p", text: "Dès qu'une nouvelle version est proposée, et en priorité en cas de plantages, de lenteurs, d'écran noir ou d'incompatibilité après un changement d'appareil. Après la mise à jour, redémarrez l'application — parfois le boîtier — pour repartir sur une base saine." },
      { type: "faq", items: [
        { q: "Mettre à jour mon lecteur efface-t-il mes chaînes ?", a: "Non, en principe vos listes et réglages sont conservés. En cas de doute, gardez votre e-mail d'activation pour reconfigurer facilement si besoin." },
        { q: "Mon application n'a pas de mise à jour disponible, est-ce normal ?", a: "Oui, si vous avez déjà la dernière version. Certaines applications à portail (IBO, Duplex) se mettent aussi à jour côté serveur, sans action de votre part." },
        { q: "Faut-il mettre à jour même si tout fonctionne ?", a: "C'est recommandé : les mises à jour préviennent les bugs et assurent la compatibilité future. Mais rien ne presse tant que tout est stable." },
      ]},
      { type: "callout", title: "À retenir", items: [
        "Une application à jour est plus stable et mieux compatible.",
        "Passez par le store de l'appareil pour mettre à jour.",
        "Mettez à jour en priorité en cas de plantages ou lenteurs.",
        "Redémarrez l'application après chaque mise à jour.",
      ]},
    ],
  },
  {
    slug: "choisir-boitier-iptv",
    title: "Quel boîtier ou clé choisir pour l'IPTV ?",
    excerpt:
      "Fire TV Stick, Android TV, Nvidia Shield, Apple TV : lequel choisir selon votre budget et vos besoins ? Notre comparatif pour équiper une télévision non connectée.",
    category: "Comparatif",
    date: "2026-07-30",
    readingMinutes: 6,
    links: [
      { label: "Fire TV Stick", href: "/appareils/firestick" },
      { label: "Android TV", href: "/appareils/android-tv" },
      { label: "Nvidia Shield", href: "/appareils/nvidia-shield" },
      { label: "Apple TV", href: "/appareils/apple-tv" },
      { label: "Fire TV Stick ou boîtier Android", href: "/blog/fire-tv-stick-ou-boitier-android" },
    ],
    body: [
      { type: "p", text: "Votre téléviseur n'est pas connecté, ou sa Smart TV est devenue trop lente ? Un boîtier ou une clé externe est la meilleure solution : quelques dizaines d'euros suffisent à transformer n'importe quel écran HDMI en plateforme IPTV performante. Ce comparatif couvre toute la gamme, du plus abordable au haut de gamme. (Pour le duel serré entre la clé Amazon et un boîtier Android, nous avons un article dédié.)" },
      { type: "h2", text: "Le comparatif de la gamme" },
      { type: "table", headers: ["Appareil", "Budget", "Points forts", "Idéal pour"], rows: [
        ["Fire TV Stick 4K", "Bas", "Simple, efficace", "Petit budget"],
        ["Boîtier Android TV", "Moyen", "Puissance, Play Store complet", "Usage quotidien"],
        ["Nvidia Shield", "Élevé", "Fluidité, durabilité", "Exigence maximale"],
        ["Apple TV 4K", "Élevé", "Fluidité, écosystème Apple", "Utilisateurs Apple"],
      ]},
      { type: "h2", text: "Fire TV Stick : le plus accessible" },
      { type: "p", text: "Économique et simple, le Fire TV Stick se branche derrière la télévision et fait très bien tourner l'IPTV. La version 4K est recommandée pour l'Ultra HD. Son seul défaut : une mémoire limitée qu'il faut ménager en n'installant que le nécessaire." },
      { type: "h2", text: "Boîtiers Android TV : le bon équilibre" },
      { type: "p", text: "Les boîtiers Android TV offrent plus de puissance et de stockage, avec un large choix d'applications via Google Play. Un bon compromis pour un usage quotidien confortable, sans se ruiner." },
      { type: "h2", text: "Nvidia Shield et Apple TV : le haut de gamme" },
      { type: "p", text: "Pour la meilleure fluidité et une 4K impeccable, la Nvidia Shield (Android TV) et l'Apple TV 4K sont des références. Plus chères, elles sont taillées pour durer et gèrent sans effort les flux les plus exigeants. L'Apple TV s'impose si vous êtes déjà dans l'écosystème Apple." },
      { type: "ul", items: ["Petit budget : Fire TV Stick 4K.", "Usage quotidien polyvalent : boîtier Android TV.", "Exigence maximale et durabilité : Nvidia Shield ou Apple TV 4K."] },
      { type: "faq", items: [
        { q: "Quel boîtier IPTV offre le meilleur rapport qualité-prix ?", a: "Pour la plupart des gens, le Fire TV Stick 4K ou un bon boîtier Android TV. La Shield et l'Apple TV se justifient surtout pour un usage intensif ou exigeant." },
        { q: "Faut-il forcément un appareil 4K ?", a: "Seulement si votre téléviseur est en Ultra HD. Sur un écran Full HD, un appareil non-4K suffit amplement." },
        { q: "Un boîtier améliore-t-il la qualité par rapport à ma Smart TV ?", a: "Il n'améliore pas l'image en soi, mais un appareil plus puissant rend l'interface plus fluide et évite les ralentissements d'une vieille Smart TV." },
      ]},
      { type: "callout", title: "À retenir", items: [
        "Fire TV Stick 4K : le meilleur rapport prix/simplicité.",
        "Android TV : l'équilibre puissance/prix pour tous les jours.",
        "Nvidia Shield / Apple TV 4K : le haut de gamme durable.",
        "Choisissez la version 4K si votre écran est en Ultra HD.",
      ]},
    ],
  },
  {
    slug: "comprendre-vod-iptv",
    title: "La vidéothèque à la demande (VOD) en IPTV expliquée",
    excerpt:
      "Au-delà des chaînes en direct, l'IPTV propose une immense vidéothèque de films et séries. Comment ça marche, et comment en profiter au mieux ?",
    category: "Guide",
    date: "2026-07-25",
    readingMinutes: 4,
    links: [
      { label: "Films & VOD", href: "/contenu/divertissement/films" },
      { label: "Séries", href: "/contenu/divertissement/series" },
      { label: "Chaînes cinéma", href: "/contenu/chaines/cinema" },
    ],
    body: [
      { type: "p", text: "Beaucoup pensent que l'IPTV se limite aux chaînes en direct. C'est oublier sa seconde moitié : la vidéothèque à la demande (VOD), qui rassemble des milliers de films et de séries que l'on lance quand on veut, exactement comme sur une plateforme de streaming. Voici comment elle fonctionne et comment en tirer le meilleur." },
      { type: "h2", text: "Comment ça fonctionne" },
      { type: "p", text: "Dans le lecteur, une section séparée regroupe les films et les séries, souvent classés par genre, par année ou par nouveauté. Vous parcourez le catalogue, choisissez un titre et la lecture démarre — avec, selon les contenus, plusieurs pistes audio et des sous-titres, ainsi que la reprise là où vous vous étiez arrêté." },
      { type: "h2", text: "Direct et VOD : deux usages complémentaires" },
      { type: "table", headers: ["", "Direct (chaînes)", "VOD (vidéothèque)"], rows: [
        ["Quand ça se regarde", "À l'heure de diffusion", "Quand vous voulez"],
        ["Choix du contenu", "La grille impose", "Vous choisissez le titre"],
        ["Idéal pour", "Sport, info, événements", "Films, séries, marathon"],
        ["Reprise / pause", "Limitée", "Oui, à tout moment"],
      ]},
      { type: "h2", text: "VF, VOST et qualité" },
      { type: "p", text: "Beaucoup de films sont proposés en version française et en version originale sous-titrée. La qualité va de la HD à la 4K selon les titres. Un bon débit reste nécessaire pour les contenus en Ultra HD, comme pour n'importe quelle vidéo haute définition." },
      { type: "h2", text: "Direct et VOD : complémentaires" },
      { type: "p", text: "Les chaînes de cinéma, en direct, offrent une programmation éditorialisée (cycles, avant-premières), tandis que la VOD vous laisse entièrement libre. Les deux ne s'opposent pas : ils se complètent, et c'est cette combinaison qui fait la richesse d'un bon abonnement." },
      { type: "faq", items: [
        { q: "La VOD est-elle incluse dans l'abonnement IPTV ?", a: "Dans la plupart des offres, oui : la vidéothèque est comprise, sans supplément par film. Vérifiez toutefois le détail de votre offre." },
        { q: "Peut-on mettre un film sur pause et le reprendre plus tard ?", a: "Oui, c'est tout l'intérêt de la VOD : vous lancez, mettez en pause et reprenez à votre rythme, contrairement au direct." },
        { q: "Le catalogue VOD est-il à jour ?", a: "Les catalogues s'enrichissent régulièrement de nouveautés. La fréquence de mise à jour dépend du service." },
      ]},
      { type: "callout", title: "À retenir", items: [
        "La VOD, c'est une vidéothèque de films et séries à lancer à la demande.",
        "Classement par genre, année et nouveautés dans le lecteur.",
        "VF et VOST disponibles selon les titres, de la HD à la 4K.",
        "Direct et VOD sont complémentaires.",
      ]},
    ],
  },
  {
    slug: "activer-iptv-rapidement",
    title: "Activer son abonnement IPTV en quelques minutes",
    excerpt:
      "Après la commande, l'activation est rapide. Voici ce qui se passe, comment récupérer vos accès et démarrer sans attendre.",
    category: "Tutoriel",
    date: "2026-07-20",
    readingMinutes: 3,
    links: [
      { label: "Comment installer l'IPTV", href: "/blog/comment-installer-iptv" },
      { label: "Essai sans risque", href: "/abonnement/essai-gratuit" },
      { label: "Nous contacter", href: "/contact" },
    ],
    body: [
      { type: "p", text: "Bonne nouvelle pour les impatients : une fois votre commande passée, l'activation ne prend généralement que quelques minutes. Pas d'installation technique compliquée, pas d'attente de plusieurs jours. Voici précisément comment cela se déroule, pour démarrer sereinement et savoir à quoi vous attendre." },
      { type: "h2", text: "1. Vous recevez vos accès" },
      { type: "p", text: "Après confirmation, vous recevez par e-mail vos identifiants d'accès : une URL, un identifiant et un mot de passe, ou un lien M3U. Ce sont ces informations que vous saisirez dans l'application — gardez cet e-mail précieusement, vous en aurez besoin à chaque nouvelle installation." },
      { type: "h2", text: "2. Vous installez un lecteur" },
      { type: "p", text: "Sur votre appareil, installez une application IPTV compatible depuis son store (IPTV Smarters est un bon choix universel), puis ajoutez vos accès via les codes Xtream ou le lien M3U." },
      { type: "h2", text: "3. Vous regardez" },
      { type: "p", text: "La liste des chaînes se charge et le guide des programmes se remplit. Vous pouvez commencer immédiatement et enregistrer vos favoris. En cas de question, le support répond en français." },
      { type: "h2", text: "Combien de temps pour chaque étape ?" },
      { type: "table", headers: ["Étape", "Durée indicative"], rows: [
        ["Réception de l'e-mail d'accès", "Quelques minutes après confirmation"],
        ["Installation du lecteur", "1 à 2 minutes"],
        ["Saisie des accès", "2 à 3 minutes"],
        ["Chargement des chaînes", "Quelques secondes"],
      ]},
      { type: "faq", items: [
        { q: "Combien de temps après la commande puis-je regarder ?", a: "En général quelques minutes : le temps de recevoir l'e-mail d'accès, d'installer un lecteur et de saisir vos identifiants." },
        { q: "Je n'ai pas reçu mon e-mail d'accès, que faire ?", a: "Vérifiez vos spams et l'adresse saisie à la commande. Sans nouvelle, contactez le support, qui répond en français." },
        { q: "Puis-je activer sur plusieurs appareils ?", a: "Vous pouvez installer le lecteur sur plusieurs appareils, mais le nombre de flux simultanés dépend de votre offre." },
      ]},
      { type: "callout", title: "À retenir", items: [
        "Activation en quelques minutes après la commande.",
        "Vos accès arrivent par e-mail (Xtream ou M3U).",
        "Installez un lecteur, saisissez vos accès, regardez.",
        "Le support vous accompagne en cas de besoin.",
      ]},
    ],
  },
  {
    slug: "erreurs-a-eviter-debutant-iptv",
    title: "Les erreurs à éviter quand on débute en IPTV",
    excerpt:
      "Wi-Fi trop faible, identifiants mal saisis, trop d'appareils… Voici les pièges classiques du débutant, et comment les éviter dès le départ.",
    category: "Conseils",
    date: "2026-07-15",
    readingMinutes: 4,
    links: [
      { label: "Buffering et coupures", href: "/problemes/buffering-coupure" },
      { label: "Débit internet nécessaire", href: "/problemes/vitesse-internet" },
      { label: "Comment installer l'IPTV", href: "/blog/comment-installer-iptv" },
    ],
    body: [
      { type: "p", text: "La plupart des mauvaises expériences en IPTV ne viennent pas du service, mais de quelques erreurs de débutant faciles à éviter. Buffering, écran noir, connexion refusée : dans l'immense majorité des cas, la cause figure dans cette liste. En les connaissant à l'avance, vous partez sur de bonnes bases et vous vous épargnez des heures de frustration." },
      { type: "h2", text: "Les pièges classiques et leur remède" },
      { type: "table", headers: ["Erreur", "Conséquence", "Remède"], rows: [
        ["Wi-Fi trop faible", "Coupures, buffering", "Se rapprocher de la box ou passer en Ethernet"],
        ["Identifiants mal saisis", "Connexion refusée", "Copier-coller, vérifier les espaces"],
        ["4K sur un débit trop juste", "Buffering permanent", "Passer en Full HD"],
        ["Application non mise à jour", "Plantages, bugs", "Mettre à jour régulièrement"],
      ]},
      { type: "h2", text: "1. Se contenter d'un Wi-Fi faible" },
      { type: "p", text: "Le Wi-Fi éloigné de la box est la première cause de coupures. Rapprochez l'appareil, ou mieux, privilégiez une connexion Ethernet, surtout pour la 4K. C'est le réglage qui règle le plus de problèmes." },
      { type: "h2", text: "2. Mal recopier ses identifiants" },
      { type: "p", text: "Un espace en trop, une lettre confondue, et la connexion échoue sans autre explication. Copiez-collez vos accès depuis l'e-mail quand c'est possible, et vérifiez l'absence d'espace au début ou à la fin." },
      { type: "h2", text: "3. Négliger la qualité choisie" },
      { type: "p", text: "Vouloir la 4K avec un débit trop juste provoque un buffering permanent. Si votre connexion est limitée, la Full HD offre une image excellente et bien plus stable — mieux vaut une image nette qui ne coupe pas qu'une 4K qui rame." },
      { type: "h2", text: "4. Ne pas mettre à jour l'application" },
      { type: "p", text: "Une application ancienne plante plus souvent et peut devenir incompatible. Gardez votre lecteur à jour pour éviter les bugs et profiter des améliorations." },
      { type: "faq", items: [
        { q: "Pourquoi mon IPTV bufferise sans arrêt ?", a: "Le plus souvent à cause d'un Wi-Fi trop faible ou d'une qualité trop élevée pour votre débit. Rapprochez-vous de la box ou passez en Full HD." },
        { q: "Ma connexion est refusée, d'où vient l'erreur ?", a: "Presque toujours d'une faute de saisie dans les identifiants (espace, majuscule) ou d'un abonnement inactif. Vérifiez avec l'e-mail sous les yeux." },
        { q: "Faut-il forcément l'Ethernet pour l'IPTV ?", a: "Non, un bon Wi-Fi suffit souvent. Mais pour la 4K ou en cas d'instabilité, l'Ethernet reste la solution la plus fiable." },
      ]},
      { type: "callout", title: "À retenir", items: [
        "Privilégiez l'Ethernet ou un Wi-Fi proche de la box.",
        "Recopiez vos identifiants sans espace superflu.",
        "Adaptez la qualité à votre débit réel.",
        "Gardez l'application à jour.",
      ]},
    ],
  },
  {
    slug: "comprendre-4k-hdr-h265",
    title: "Comprendre la 4K, le HDR et le H.265 en IPTV",
    excerpt:
      "Ces termes reviennent partout, mais que signifient-ils vraiment ? On démystifie la 4K, le HDR et le codec H.265 pour bien comprendre la qualité d'image.",
    category: "Guide",
    date: "2026-07-11",
    readingMinutes: 4,
    links: [
      { label: "IPTV en 4K : matériel et conditions", href: "/blog/iptv-4k-materiel-et-conditions" },
      { label: "Image de mauvaise qualité", href: "/problemes/image-qualite" },
      { label: "Les formats vidéo", href: "/formats" },
    ],
    body: [
      { type: "p", text: "4K, HDR, H.265 : ces sigles reviennent sur toutes les fiches produits et dans tous les menus, souvent mélangés comme s'ils voulaient dire la même chose. En réalité, ils décrivent trois aspects bien distincts de l'image. Les comprendre — sans jargon — aide à choisir son matériel et à régler correctement son lecteur. Voici la différence, résumée dans un tableau." },
      { type: "h2", text: "Trois notions, trois rôles" },
      { type: "table", headers: ["Terme", "Ce qu'il décrit", "Ce qu'il apporte"], rows: [
        ["4K (Ultra HD)", "La résolution", "Plus de détails (4× la Full HD)"],
        ["HDR", "Le contraste et les couleurs", "Image plus vivante et nuancée"],
        ["H.265 (HEVC)", "La compression", "La 4K possible sans saturer la connexion"],
      ]},
      { type: "h2", text: "La 4K : plus de détails" },
      { type: "p", text: "La 4K (ou Ultra HD) désigne la résolution : environ 3840 × 2160 pixels, soit quatre fois la Full HD. Plus il y a de pixels, plus l'image est détaillée — un gain surtout visible sur un grand écran ou de près." },
      { type: "h2", text: "Le HDR : plus de contraste et de couleurs" },
      { type: "p", text: "Le HDR (High Dynamic Range) ne concerne pas la résolution mais la richesse de l'image : des noirs plus profonds, des blancs plus lumineux et des couleurs plus nuancées. Un contenu HDR sur un écran compatible paraît visiblement plus vivant, parfois plus que le simple passage à la 4K." },
      { type: "h2", text: "Le H.265 : une compression efficace" },
      { type: "p", text: "Le H.265 (HEVC) est un codec, c'est-à-dire une méthode de compression. Il permet de diffuser de la 4K en consommant beaucoup moins de bande passante que l'ancien H.264. C'est lui, en coulisses, qui rend le streaming 4K possible sur une connexion domestique classique." },
      { type: "faq", items: [
        { q: "La 4K et le HDR, c'est pareil ?", a: "Non. La 4K augmente le nombre de pixels (netteté), le HDR améliore contraste et couleurs. Les deux sont indépendants et se cumulent." },
        { q: "Faut-il un écran spécial pour le H.265 ?", a: "Le H.265 est un format de compression géré par l'appareil de lecture. La plupart des appareils récents le décodent ; les plus anciens peuvent avoir du mal avec la 4K en H.265." },
        { q: "Mon écran n'est pas 4K, l'IPTV fonctionne quand même ?", a: "Bien sûr. Vous profitez alors de la HD ou Full HD, très satisfaisante. La 4K n'a d'intérêt que sur un écran compatible." },
      ]},
      { type: "callout", title: "À retenir", items: [
        "4K = résolution (nombre de pixels).",
        "HDR = contraste et richesse des couleurs.",
        "H.265 (HEVC) = compression efficace qui rend la 4K fluide.",
        "Pour en profiter, il faut un contenu, un appareil et un écran compatibles.",
      ]},
    ],
  },
  {
    slug: "iptv-et-sport-tout-suivre",
    title: "IPTV et sport : comment tout suivre en une seule offre",
    excerpt:
      "Ligue 1, Champions League, F1, NBA, rugby… Les droits sont éclatés entre diffuseurs. Voici comment l'IPTV réunit le sport au même endroit.",
    category: "Guide",
    date: "2026-07-08",
    readingMinutes: 5,
    links: [
      { label: "Tout le sport en direct", href: "/contenu/sport" },
      { label: "Regarder la Ligue 1", href: "/contenu/sport/ligue-1" },
      { label: "Regarder la Champions League", href: "/contenu/sport/champions-league" },
      { label: "Chaînes de sport (beIN, Canal+…)", href: "/contenu/sport/bein-sports" },
    ],
    body: [
      { type: "p", text: "Entre le foot du samedi, la F1 du dimanche et la NBA de la nuit, suivre tout le sport en France est devenu un casse-tête — et un budget. Les droits sont répartis entre une poignée de diffuseurs, ce qui oblige à cumuler les abonnements pour ne rien manquer. L'IPTV apporte une réponse simple en réunissant ces sources au même endroit. Voici comment, et sur quel critère juger un service pour le sport." },
      { type: "h2", text: "Un paysage éclaté" },
      { type: "p", text: "Chaque compétition a son diffuseur, et cela bouge d'une saison à l'autre. Résultat : impossible de tout avoir sans multiplier les abonnements. Voici un aperçu du morcellement typique." },
      { type: "table", headers: ["Compétition", "Diffuseurs habituels"], rows: [
        ["Ligue 1", "Partagée entre plusieurs chaînes"],
        ["Champions League", "Surtout Canal+"],
        ["Liga, Serie A", "beIN Sports"],
        ["Formule 1", "Canal+"],
        ["Cyclisme, sports variés", "Eurosport"],
      ]},
      { type: "h2", text: "L'IPTV comme point d'accès unique" },
      { type: "p", text: "Avec un service IPTV, vous retrouvez ces chaînes réunies dans une seule application. Vous passez d'un match de Ligue 1 à une course de F1 ou à un match NBA sans changer de plateforme ni jongler entre les identifiants, en Full HD ou en 4K." },
      { type: "ul", items: ["Football : Ligue 1, Champions League, Premier League, Liga, Serie A…", "Sport auto : Formule 1, MotoGP.", "Tennis, rugby, cyclisme, basket, boxe et MMA.", "Grands événements : Coupe du monde, Euro, Roland-Garros, Tour de France."] },
      { type: "h2", text: "La stabilité, critère numéro un" },
      { type: "p", text: "Le sport est l'usage le plus exigeant qui soit : c'est lors des grands soirs, quand des milliers de spectateurs se connectent en même temps, que les serveurs sont mis à l'épreuve. Une connexion filaire et un service dimensionné pour les pics d'audience font toute la différence entre une soirée fluide et une image qui se fige au but décisif." },
      { type: "faq", items: [
        { q: "Peut-on vraiment suivre tous les sports avec une seule offre ?", a: "L'IPTV réunit les chaînes sportives dans une seule application, ce qui couvre l'essentiel des compétitions au même endroit, sans cumuler les abonnements." },
        { q: "Quelle est la qualité pour le sport en direct ?", a: "Selon les chaînes, de la Full HD à la 4K. Une bonne définition demande un débit stable, particulièrement les soirs de forte affluence." },
        { q: "Comment éviter les coupures pendant un grand match ?", a: "Privilégiez une connexion Ethernet sur le poste principal et un service réputé pour sa stabilité aux heures de pointe." },
      ]},
      { type: "callout", title: "À retenir", items: [
        "Les droits sportifs sont éclatés entre plusieurs diffuseurs.",
        "L'IPTV réunit ces chaînes dans une seule application.",
        "Football, F1, tennis, rugby, basket, combat… tout au même endroit.",
        "Pour les grands soirs, privilégiez l'Ethernet.",
      ]},
    ],
  },
  {
    slug: "controle-parental-iptv",
    title: "Contrôle parental et IPTV : protéger ses enfants",
    excerpt:
      "Verrouiller certaines chaînes, créer un profil adapté, encadrer les horaires : voici comment mettre en place un contrôle parental efficace sur votre IPTV.",
    category: "Conseils",
    date: "2026-07-02",
    readingMinutes: 4,
    links: [
      { label: "Chaînes jeunesse", href: "/contenu/chaines/enfants" },
      { label: "IPTV en famille", href: "/blog/iptv-multi-ecrans-famille" },
    ],
    body: [
      { type: "p", text: "Un catalogue de dizaines de milliers de chaînes et de films, c'est formidable — mais cela mérite un peu d'encadrement dès que des enfants regardent. Bonne nouvelle : la plupart des lecteurs IPTV intègrent des outils simples de contrôle parental, qui prennent quelques minutes à mettre en place. Voici comment protéger efficacement, sans transformer chaque séance télé en casse-tête." },
      { type: "h2", text: "Trois niveaux de protection" },
      { type: "table", headers: ["Outil", "Ce qu'il fait", "Effort de mise en place"], rows: [
        ["Code PIN sur chaînes/catégories", "Bloque l'accès sans le code", "Faible"],
        ["Masquage des catégories adultes", "Les rend invisibles", "Faible"],
        ["Profil ou mode enfant", "Ne montre que le contenu jeunesse", "Moyen (selon le lecteur)"],
      ]},
      { type: "h2", text: "Verrouiller des chaînes ou des catégories" },
      { type: "p", text: "La majorité des applications permettent de protéger par code PIN certaines chaînes ou catégories entières. Une fois verrouillées, elles ne sont accessibles qu'après saisie du code — simple et efficace pour les contenus sensibles." },
      { type: "h2", text: "Créer un accès adapté aux enfants" },
      { type: "p", text: "Vous pouvez masquer les catégories réservées aux adultes et ne laisser visibles que les chaînes jeunesse et familiales. Sur certains lecteurs, un mode ou un profil dédié facilite cette configuration, l'enfant ne voyant alors que ce qui lui est destiné." },
      { type: "h2", text: "Encadrer sans compliquer" },
      { type: "ul", items: ["Choisissez un code PIN que les enfants ne connaissent pas.", "Masquez les catégories inadaptées plutôt que de tout verrouiller.", "Mettez en favoris les chaînes jeunesse pour un accès simple.", "Vérifiez les réglages après chaque mise à jour de l'application."] },
      { type: "faq", items: [
        { q: "Tous les lecteurs IPTV ont-ils un contrôle parental ?", a: "La plupart proposent au moins un verrouillage par code PIN. Les fonctions avancées (profils enfant) varient selon l'application." },
        { q: "Comment empêcher un enfant de voir les catégories adultes ?", a: "Masquez ces catégories dans les réglages et protégez-les par un code PIN qu'il ne connaît pas." },
        { q: "Mes réglages disparaissent après une mise à jour, est-ce normal ?", a: "Certains lecteurs réinitialisent les réglages lors d'une réinstallation. Vérifiez le contrôle parental après chaque mise à jour importante." },
      ]},
      { type: "callout", title: "À retenir", items: [
        "La plupart des lecteurs proposent un verrouillage par code PIN.",
        "Masquez les catégories inadaptées et mettez la jeunesse en favoris.",
        "Choisissez un code que les enfants ignorent.",
        "Revérifiez les réglages après les mises à jour.",
      ]},
    ],
  },
  {
    slug: "pourquoi-iptv-moins-cher",
    title: "Pourquoi l'IPTV coûte moins cher que le câble ou le satellite",
    excerpt:
      "À catalogue équivalent, l'IPTV est souvent bien moins chère que les offres traditionnelles. On explique pourquoi, sans discours marketing.",
    category: "Guide",
    date: "2026-06-26",
    readingMinutes: 4,
    links: [
      { label: "Nos formules d'abonnement", href: "/abonnement" },
      { label: "IPTV pas cher", href: "/abonnement/pas-cher" },
      { label: "Comment choisir son abonnement", href: "/blog/comment-choisir-son-abonnement-iptv" },
    ],
    body: [
      { type: "p", text: "À première vue, l'écart de prix entre l'IPTV et une offre câble ou satellite a de quoi surprendre — parfois du simple au triple à catalogue comparable. Rassurez-vous, il ne cache aucun tour de magie : il s'explique par des différences concrètes de fonctionnement. Les comprendre aide aussi à distinguer un prix bas légitime d'une offre « trop belle pour être vraie »." },
      { type: "h2", text: "D'où vient l'écart de prix" },
      { type: "table", headers: ["Poste de coût", "Câble / satellite", "IPTV"], rows: [
        ["Infrastructure", "Satellites, réseaux physiques", "Internet existant"],
        ["Matériel", "Décodeur / parabole imposés", "Vos appareils actuels"],
        ["Installation", "Souvent nécessaire", "Aucune"],
        ["Engagement", "Long (12-24 mois)", "Souvent sans engagement"],
      ]},
      { type: "h2", text: "Pas d'infrastructure lourde" },
      { type: "p", text: "Le satellite et le câble reposent sur des infrastructures coûteuses : satellites, réseaux physiques, installation, matériel dédié. L'IPTV, elle, utilise l'internet que vous avez déjà, sans parabole ni décodeur propriétaire — autant de coûts qui disparaissent de la facture." },
      { type: "h2", text: "Pas de matériel imposé" },
      { type: "p", text: "Avec l'IPTV, vous regardez sur vos appareils actuels — Smart TV, boîtier, mobile. Aucun décodeur à louer chaque mois, aucun équipement à acheter, ce qui réduit d'autant le prix." },
      { type: "h2", text: "Souplesse et absence d'engagement" },
      { type: "p", text: "Les offres traditionnelles imposent souvent des engagements longs et des options en supplément. L'IPTV mise sur des formules courtes, sans engagement, ce qui évite de payer pour des mois inutilisés." },
      { type: "h2", text: "Attention tout de même" },
      { type: "p", text: "Un prix plus bas s'explique par ces économies réelles — mais un prix dérisoire, ou une offre « à vie », ne s'explique pas de façon saine. Là, la prudence s'impose : un tarif raisonnable n'est pas la même chose qu'un tarif suspect." },
      { type: "faq", items: [
        { q: "L'IPTV est-elle vraiment moins chère à catalogue égal ?", a: "Oui, généralement, car elle supprime les coûts d'infrastructure et de matériel du câble ou du satellite, et évite les engagements longs." },
        { q: "Un prix bas cache-t-il forcément une arnaque ?", a: "Non. Un prix bas peut être parfaitement légitime. C'est le prix dérisoire ou « à vie », associé à un manque de transparence, qui doit alerter." },
        { q: "Ai-je besoin d'un matériel spécial ?", a: "Non : vos appareils actuels (Smart TV, boîtier, mobile) suffisent, éventuellement complétés d'une clé ou d'un boîtier à quelques dizaines d'euros." },
      ]},
      { type: "callout", title: "À retenir", items: [
        "Pas d'infrastructure lourde ni de parabole à financer.",
        "Vous utilisez vos appareils actuels, sans matériel imposé.",
        "Des formules souples, souvent sans engagement.",
        "Méfiez-vous cependant des prix anormalement bas (voir nos conseils anti-arnaque).",
      ]},
    ],
  },
  {
    slug: "quel-forfait-internet-pour-iptv",
    title: "Quelle connexion internet pour l'IPTV ? Fibre, débit et box",
    excerpt:
      "ADSL ou fibre, quel débit, quelle box : voici comment savoir si votre connexion est adaptée à l'IPTV, et comment l'optimiser.",
    category: "Guide",
    date: "2026-06-20",
    readingMinutes: 9,
    links: [
      { label: "Wi-Fi ou Ethernet : que choisir", href: "/blog/wifi-ou-ethernet-pour-iptv" },
      { label: "Comment tester son débit", href: "/blog/comment-tester-son-debit-pour-iptv" },
      { label: "Comprendre la latence et le buffer", href: "/blog/comprendre-la-latence-et-le-buffer" },
      { label: "Débit internet nécessaire", href: "/problemes/vitesse-internet" },
      { label: "IPTV bloqué par l'opérateur", href: "/problemes/iptv-bloque-operateur" },
    ],
    body: [
      { type: "p", text: "Vous hésitez à passer à l'IPTV et vous vous demandez si votre connexion « tiendra » ? C'est la bonne question à se poser en premier : contrairement à une box TV classique reliée à un décodeur, l'IPTV fait transiter chaque chaîne par votre accès internet, en continu. Ce guide vous aide à évaluer votre connexion actuelle, à comprendre ce qui compte vraiment (et ce qui compte moins), et à savoir quoi améliorer si besoin — sans jargon inutile." },
      { type: "h2", text: "Pourquoi la connexion est le facteur numéro un" },
      { type: "p", text: "Quand une image se fige ou qu'une chaîne met du temps à démarrer, on accuse souvent « le serveur ». Dans les faits, la grande majorité des ralentissements se jouent sur le dernier maillon : votre réseau domestique. C'est la partie sur laquelle vous avez le plus de contrôle, et souvent celle qui fait toute la différence entre une soirée fluide et une soirée frustrante." },
      { type: "p", text: "Trois éléments comptent : le débit (la quantité de données par seconde), la stabilité (ce débit reste-t-il constant ?) et la façon dont l'appareil est relié à la box. On les passe en revue un par un." },
      { type: "h2", text: "ADSL, VDSL ou fibre : que vaut chaque technologie ?" },
      { type: "h3", text: "L'ADSL" },
      { type: "p", text: "L'ADSL offre généralement de 1 à 15 Mb/s selon votre éloignement du central téléphonique. Il peut convenir à la haute définition si le débit est régulier, mais il montre vite ses limites en 4K, en multi-écrans ou aux heures de pointe, quand plusieurs foyers du quartier sollicitent la même ligne." },
      { type: "h3", text: "Le VDSL" },
      { type: "p", text: "Le VDSL2, disponible sur les lignes courtes, monte à quelques dizaines de Mb/s. C'est un bon compromis là où la fibre n'est pas encore déployée : suffisant pour la Full HD confortable et un peu de simultané." },
      { type: "h3", text: "La fibre" },
      { type: "p", text: "La fibre optique apporte non seulement un débit élevé (souvent 300 Mb/s à plusieurs Gb/s) mais surtout une stabilité que le cuivre n'atteint pas. C'est le choix idéal pour la 4K, le multi-écrans et les foyers où l'on regarde beaucoup en simultané." },
      { type: "h2", text: "Le débit dont vous avez réellement besoin" },
      { type: "p", text: "Contrairement à une idée répandue, il ne faut pas un abonnement à 1 Gb/s pour profiter de l'IPTV. Ce qui compte, c'est un débit stable adapté à la définition que vous regardez :" },
      { type: "table", headers: ["Définition", "Débit conseillé (par flux)", "Adapté à"], rows: [
        ["SD (définition standard)", "3–5 Mb/s", "Petits écrans, connexions modestes"],
        ["HD 720p", "5–8 Mb/s", "La plupart des chaînes"],
        ["Full HD 1080p", "10–15 Mb/s", "Grand téléviseur, confort quotidien"],
        ["4K Ultra HD", "25 Mb/s et plus", "Grandes TV récentes, cinéma, sport"],
      ]},
      { type: "p", text: "Ces valeurs sont à multiplier par le nombre d'écrans utilisés en même temps : deux téléviseurs en Full HD demandent environ le double. Pour bien dimensionner un foyer familial, voyez notre guide sur le multi-écrans." },
      { type: "h2", text: "Le débit ne fait pas tout : stabilité et latence" },
      { type: "p", text: "Une connexion peut afficher un bon débit moyen et pourtant provoquer des coupures, parce que ce débit chute par à-coups. La régularité prime souvent sur la vitesse maximale. Le délai d'affichage au changement de chaîne, lui, dépend d'autres facteurs que nous détaillons dans notre article dédié à la latence et au buffer." },
      { type: "h2", text: "Votre box et votre routeur comptent autant que l'abonnement" },
      { type: "p", text: "Un excellent abonnement fibre desservi par un Wi-Fi mal placé donnera une expérience médiocre. Quelques points font une vraie différence :" },
      { type: "ul", items: [
        "L'âge de la box : un modèle récent gère mieux le Wi-Fi et les flux multiples.",
        "La distance et les murs : chaque cloison réduit le signal Wi-Fi.",
        "La bande utilisée : le 5 GHz est plus rapide à courte portée que le 2,4 GHz.",
        "Le nombre d'appareils connectés : téléphones, consoles et objets connectés se partagent la bande passante.",
      ]},
      { type: "p", text: "Pour le téléviseur principal, la question du Wi-Fi contre le câble mérite un choix réfléchi — nous la traitons en détail dans notre comparatif Wi-Fi ou Ethernet." },
      { type: "h2", text: "Faut-il absolument la fibre ?" },
      { type: "p", text: "Non. La fibre est confortable mais pas obligatoire : une bonne ligne VDSL, voire un ADSL stable, permet de regarder l'IPTV en HD sans souci. La fibre devient vraiment utile dès que vous visez la 4K régulière ou plusieurs écrans simultanés. Si vous êtes en ADSL et que tout fonctionne en Full HD, inutile de changer d'offre pour l'IPTV seule." },
      { type: "h2", text: "Vérifier votre connexion avant de vous décider" },
      { type: "p", text: "La meilleure preuve reste la mesure. Faites un test de débit sur l'appareil qui lira réellement l'IPTV, connecté comme en usage réel, et de préférence le soir. Notre guide pas à pas vous explique comment tester et surtout comment interpréter le résultat." },
      { type: "faq", items: [
        { q: "L'ADSL suffit-il pour l'IPTV ?", a: "Oui pour la HD, si le débit est stable (autour de 8 Mb/s). Pour la 4K ou plusieurs écrans en même temps, la fibre est nettement plus confortable." },
        { q: "Quel débit pour regarder à deux en 4K ?", a: "Comptez environ 25 Mb/s par flux 4K, soit au moins 50 Mb/s stables pour deux téléviseurs en Ultra HD simultanés." },
        { q: "La fibre garantit-elle l'absence de coupures ?", a: "Elle réduit fortement le risque, mais une coupure peut aussi venir d'un Wi-Fi faible, d'un appareil saturé ou d'un bridage de l'opérateur. La fibre aide, elle ne fait pas tout." },
        { q: "Le débit montant (upload) a-t-il une importance ?", a: "Très peu pour regarder l'IPTV : c'est le débit descendant (download) qui compte, puisque vous recevez les flux. L'upload n'intervient que de façon marginale." },
      ]},
      { type: "callout", title: "À retenir", items: [
        "L'IPTV dépend de votre réseau : c'est le premier point à vérifier.",
        "Visez ~10–15 Mb/s stables par flux Full HD, 25 Mb/s pour la 4K.",
        "La stabilité compte souvent plus que la vitesse maximale.",
        "La fibre est idéale mais pas obligatoire : un ADSL stable suffit en HD.",
        "Testez votre débit le soir, sur l'appareil concerné, avant de conclure.",
      ]},
    ],
  },
  {
    slug: "configurer-favoris-et-epg",
    title: "Configurer ses favoris et le guide des programmes (EPG)",
    excerpt:
      "Deux réglages qui changent le confort au quotidien : organiser ses chaînes favorites et afficher un guide des programmes complet. Voici comment faire.",
    category: "Tutoriel",
    date: "2026-06-14",
    readingMinutes: 4,
    links: [
      { label: "Le guide des programmes ne s'affiche pas", href: "/problemes/epg-ne-safiche-pas" },
      { label: "Comprendre l'EPG", href: "/formats/epg" },
      { label: "Toutes les applications", href: "/applications" },
    ],
    body: [
      { type: "p", text: "Une fois l'IPTV installée, deux réglages souvent négligés font pourtant toute la différence au quotidien : les favoris, pour retrouver ses chaînes d'un geste au lieu de faire défiler des milliers de lignes, et l'EPG, pour savoir ce qui passe et quand. Cinq minutes de configuration, et votre confort d'usage change du tout au tout." },
      { type: "h2", text: "Organiser ses favoris" },
      { type: "p", text: "Dans la plupart des lecteurs, un appui long (ou une icône en forme d'étoile ou de cœur) ajoute une chaîne aux favoris. Regroupez ainsi vos chaînes du quotidien dans une catégorie « Favoris » accessible en un clic. L'astuce qui change tout : créez plusieurs listes de favoris par usage — une pour le sport, une pour le cinéma, une pour les enfants." },
      { type: "h2", text: "Activer et régler l'EPG" },
      { type: "p", text: "L'EPG (guide des programmes) s'affiche automatiquement sur la plupart des lecteurs. S'il est vide ou décalé, la cause est presque toujours simple à corriger — voici les deux réglages à vérifier en priorité." },
      { type: "table", headers: ["Symptôme EPG", "Cause probable", "Solution"], rows: [
        ["Guide vide", "EPG non chargé", "Recharger la liste / l'EPG"],
        ["Horaires décalés", "Mauvais fuseau horaire", "Régler sur l'heure de Paris"],
        ["Chaînes sans programme", "Source sans EPG", "Vérifier l'accès (Xtream de préférence)"],
      ]},
      { type: "h2", text: "Quelques bonnes pratiques" },
      { type: "ul", items: ["Créez une catégorie de favoris par usage (sport, cinéma, enfants).", "Rechargez l'EPG après une mise à jour de la liste.", "Réglez le fuseau horaire pour un guide à l'heure exacte.", "Sauvegardez vos réglages si le lecteur le permet."] },
      { type: "faq", items: [
        { q: "Pourquoi mon guide des programmes est-il vide ?", a: "Le plus souvent l'EPG n'a pas été chargé, ou la source n'en fournit pas. Rechargez la liste et privilégiez un accès Xtream Codes, qui inclut généralement l'EPG." },
        { q: "Mon EPG affiche de mauvais horaires, comment corriger ?", a: "C'est presque toujours un problème de fuseau horaire dans les réglages du lecteur : réglez-le sur l'heure de Paris." },
        { q: "Mes favoris disparaissent après une mise à jour, pourquoi ?", a: "Certains lecteurs réinitialisent les réglages lors d'une réinstallation. Utilisez la sauvegarde des réglages si votre lecteur la propose." },
      ]},
      { type: "callout", title: "À retenir", items: [
        "Les favoris évitent de faire défiler des milliers de chaînes.",
        "L'EPG indique les programmes en cours et à venir.",
        "Un EPG décalé vient presque toujours du fuseau horaire.",
        "Rechargez le guide après chaque mise à jour de la liste.",
      ]},
    ],
  },
];

// Inject a central featured image when a post doesn't define its own.
function withHero(p: Post): Post {
  if (p.heroImage) return p;
  const hero = BLOG_HEROES[p.slug];
  return hero ? { ...p, heroImage: hero } : p;
}

const ALL_POSTS: Post[] = [...POSTS, ...EXTRA_POSTS].map(withHero);

export function getAllPosts(): Post[] {
  return [...ALL_POSTS].sort((a, b) => (a.date < b.date ? 1 : -1));
}

export function getPostBySlug(slug: string): Post | undefined {
  return ALL_POSTS.find((p) => p.slug === slug);
}

export function formatDate(iso: string): string {
  return new Date(iso).toLocaleDateString("fr-FR", {
    day: "numeric",
    month: "long",
    year: "numeric",
  });
}
